/////////////////////////////////////////////////////////////
// cxr_test.h
//
// This file was generated by CXR, the literal string encryptor.
// CXR, Copyright 2002, Smaller Animals Software, Inc., all rights reserved.
//
// Please do not edit this file. Any changes here will be overwritten on the next compile.
// If you wish to make changes to a string, please edit:
//     test.cxr
//

/////////////////////////////////////////////////////////////

#pragma once
#include "cxr_inc.h"

// cxr 적용 테스트입니당

///////////////////////////
#ifdef _USING_CXR
#define STR_CXRTEST1 	_CXR("\x85\x88\x8d\x88\x89\x8a\x89\x82\x8c\x89\x89\x8d\x81\x8b\x86\x8a\x8b\x8e\x83\x86\x88\x8b\x81\x83\x86\x8b\x88\x8e\x8c\x80\x83\x86\x8f\x85\x87\x8d\x89\x87\x88\x8a\x83\x82\x84\x83\x86\x89\x8a\x86\x83\x85\x82\x88\x85\x86\x8e\x85\x8f\x8f\x85\x82\x8a\x80\x88\x8e\x80\x85")
#else
#define STR_CXRTEST1 _CXR("Your all bases are belong to us.")
#endif

///////////////////////////
#ifdef _USING_CXR
#define STR_CXRTEST2 	_CXR("\x8c\x81\x84\x80\x87\x81\x8c\x8b\x85\x8a\x80\x8e\x8b\x89\x82\x81\x80\x8b\x86\x8d")// 디파인 뒤에 주석이 달린 경우를 테스트
#else
#define STR_CXRTEST2 _CXR("It's You!")// 디파인 뒤에 주석이 달린 경우를 테스트
#endif

///////////////////////////
#ifdef _USING_CXR
#define STR_CXRTEST3 	_CXR("\x8f\x85\x82\x82\x84\x80\x8d\x8a\x86\x86")		// 디파인 뒤에 공백을 두고 주석이 달린 경우를 테스트
#else
#define STR_CXRTEST3 _CXR("Aye.")		// 디파인 뒤에 공백을 두고 주석이 달린 경우를 테스트
#endif


